# Generated by Django 3.0.4 on 2020-03-19 16:23

from django.db import migrations
from property.models import Flat

def fill_new_building(apps, schema_editor):
    for flat in Flat.objects.all():
        flat.new_building = (not flat.construction_year < 2015)
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building),
    ]