# Generated by Django 3.0.4 on 2020-03-30 06:17

from django.db import migrations
from property.models import Flat
import phonenumbers


def fix_phonenumbers(apps, schema_editor):
    for flat in Flat.objects.all():
        owners_phonenumber_parse = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if not phonenumbers.is_valid_number(owners_phonenumber_parse):
            flat.owner_phone_pure = ''
            flat.save()
            continue
        flat.owner_phone_pure = owners_phonenumber_parse
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200330_1313'),
    ]

    operations = [
        migrations.RunPython(fix_phonenumbers,),
    ]
