# Generated by Django 3.0.4 on 2020-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200330_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ManyToManyField(max_length=200, related_name='owner_flats', to='property.Owner', verbose_name='ФИО владельца'),
        ),
    ]
